### ISSUE TITLE
Add ability to codegen a single expression in a given context

### ISSUE THREAD

**Issue by disnet** [shapesecurity/shift-java#108]

**Comment by bakkot** [comment]
What sort of context are you looking for?

**Comment by michaelficarra** [comment]
Statement list context, top level context, expression context parameterised by precedence level, possibly others.

**Comment by michaelficarra** [comment]
It occurs to me that this is not possible for all expressions in all contexts. For example, it is impossible to generate a `yield` IdentifierExpression in a generator context or an `eval` BindingIdentifier in a strict mode code context.

**Comment by bakkot** [comment]
Does context make any difference other than a.) is this legal and b.) is it surrounded by parentheses? I'm having trouble thinking of examples where you'd need context otherwise.

## 

Proposed more general solution: a CodeGen analogue to ParserWithLocation, which would codegen and also give you a data structure in which you could look up a node to find the range of codegen'd text corresponding to that node.

Given this, it would be easy to write a helper function to codegen an expression (or, indeed, anything else) in a particular context for absolutely an definition of 'context'.

**Comment by michaelficarra** [comment]
That's a great idea! 👍
