### ISSUE TITLE
Add support for source location

### ISSUE THREAD

**Issue by gorkem** [shapesecurity/shift-java#92]
SourceLocation is part of the shift-ast specification but it is not implemented for the Node interface. Implementation probably requires Node interface to become an abstract class implementation but since Node interface is referenced from all the AST model classes, it is best to build this change to model generator.

**Comment by ariya** [comment]
@ikarienator Do we have this in our roadmap?

**Comment by michaelficarra** [comment]
Yes, we do, but we're not sure yet how to best implement it.

**Comment by steindani** [comment]
I'd also like to access the location of the nodes. Since the project targets Java 8, what do you think about using a common HashMap storage for node-location pairs and a getter method implemented in the `Node` interface itself using a [default method](https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html)? This does not need such an invasive modification and when a change may occur, the interface could stay the same?

**Comment by michaelficarra** [comment]
This was fixed by #101.
